name: Deploy to EC2

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.8'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Deploy via SSH
      uses: appleboy/ssh-action@v0.1.10
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USER }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          sudo -i
          cd /home/ubuntu/
          cd gitrep/
          cd test-automation-framework/
          git pull
          rm -rf venv
          python3 -m venv venv
          source venv/bin/activate
          pip install -r requirements.txt
          python app/main.py

    - name: Run tests and generate report
      run: |
        mkdir -p reports
        PYTHONPATH=. pytest --html=reports/report.html

    - name: Upload HTML report
      uses: actions/upload-artifact@v4
      with:
        name: test-report
        path: reports/report.html
